# Local configuration overrides.
# These settings will be merged with the default config.toml.

[viewer]
log_level = "DEBUG"

[network]
api_base_url = "https://api.dev.example.com"
timeout = 30

[updates]
github_repo = "my-fork/my-repo"
