# Configuration for Meetscribe

[deepgram]
# Your Deepgram API key. This is a required setting.
# You can get an API key from https://console.deepgram.com/
api_key = ""

# Model and language
model = "nova-3"       # Default to Nova-3
language = "en-US"

# Formatting
smart_format = true    # punctuation, capitalization, etc.

# Diarization
diarize = true
diarize_speakers = 0   # 0 = unset; set >0 to hint expected speakers
min_speaker_gap = 0.0  # seconds; 0.0 = unset
max_speaker_gap = 0.0  # seconds; 0.0 = unset

# Enrichments
summarize = false # "v2" as altenative
detect_topics = false
intents = false

[paths]
# Default folder for storing meeting notes.
output_folder = "~/Documents/Meetscribe"
# Default folder for input audio files.
input_folder = "~/Audio"

[processing]
# When true, reprocess audio files even if the output .txt already exists (overwrite).
# Default is false, which skips files that already have outputs.
reprocess = false
soft_limit_files = 10
hard_limit_files = 25

[ui]
selection_page_size = 10

[logging]
# Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = "INFO"
# Path to log file (optional). If not set, defaults to ~/.meetscribe/meetscribe.log
log_file = "~/.meetscribe/meetscribe.log"
# Enable file logging
enable_file_logging = true

[google]
# Google Calendar integration settings
credentials_file = "~/.meetscribe/google/credentials.json"
token_file = "~/.meetscribe/google/token.json"
scopes = ["https://www.googleapis.com/auth/calendar.readonly"]
calendar_id = "primary"
default_past_days = 3
max_results = 50
filter_group_events_only = true

[llm]
# LLM post-processing configuration
enabled = true
dialect = "openai"
base_url = ""  # set to your LiteLLM proxy URL if used
api_key = ""   # leave empty; set in config.local.toml
model = "gpt-4o-mini"
temperature = 0.2
default_modes = ""  # Default is none. Set to "Q", "WE", or "QWE" to preselect modes.

[llm.prompts]
q = "Write a clear, concise executive summary of the meeting. Include key points, decisions, risks, and next steps."
w = "Provide a holistic analysis of the meeting. Summarize themes, sentiments by participants, points of alignment or tension, and overall tone."
e = "Extract a precise, actionable list of tasks discussed. For each, include assignee (if known), due date (if mentioned), and concise description."

[llm.paths]
# Optional overrides; defaults to main output_folder when empty
q_output_folder = ""
w_output_folder = ""
e_output_folder = ""

[llm.keys]
q = "Q"
w = "W"
e = "E"
