# Configuration for Meetscribe

[deepgram]
# Your Deepgram API key. This is a required setting.
# You can get an API key from https://console.deepgram.com/
api_key = ""

[paths]
# Default folder for storing meeting notes.
output_folder = "~/Documents/Meetscribe"
