name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Lint with ruff
      run: |
        python -m ruff check app/ tests/ --select=E9,F --statistics
        python -m ruff check app/ tests/ --exit-zero --line-length=127 --statistics

    - name: Run tests
      run: |
        python -m pytest --cov=app --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Verify build requirements
      run: |
        if [ ! -f "meetscribe.spec" ]; then
          echo "❌ ERROR: meetscribe.spec not found"
          exit 1
        fi
        if [ ! -f "app/cli.py" ]; then
          echo "❌ ERROR: app/cli.py not found"
          exit 1
        fi
        echo "✅ Build requirements verified"

    - name: Build executable
      run: pyinstaller meetscribe.spec

    - name: Test executable
      run: ./dist/meetscribe --help

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: meetscribe-ubuntu
        path: dist/
        retention-days: 7
